version: '3.8'

services:

  eureka:
    build: ./disc_service_eureka_server
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - springnet

  product-service:
    build: ./disc_service_product_service
    container_name: product-service
    depends_on:
      - eureka
    ports:
      - "8081:8081"
    networks:
      - springnet

  order-service:
    build: ./disc_service_order_service
    container_name: order-service
    depends_on:
      - eureka
    ports:
      - "8082:8082"
    networks:
      - springnet

networks:
  springnet:
    driver: bridge